services:
  db:
    image: postgres:15-alpine
    container_name: mt-db
    restart: always
    environment:
      POSTGRES_DB: moneytracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mt-network

  backend:
    build: ./backend
    container_name: mt-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moneytracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    networks:
      - mt-network

  frontend:
    image: node:20-alpine  # Обновил до 20 версии для совместимости с новыми реакт-роутерами
    container_name: mt-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Хак: чтобы не перезатирать node_modules из хоста
    ports:
      - "3000:3000"        # CRA использует порт 3000
    environment:
      REACT_APP_API_URL: http://localhost:8080/api  # Важно: префикс REACT_APP_
    command: sh -c "npm install && npm start"   # Команда для CRA
    depends_on:
      - backend
    networks:
      - mt-network

networks:
  mt-network:
    driver: bridge

volumes:
  pgdata: