services:

  db-dev:
    image: postgres:15-alpine
    container_name: mt-db-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - mt-network-dev

  keycloak-dev:
    image: keycloak/keycloak:26.3.2
    container_name: mt-kc-dev
    env_file:
      - .env.dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_DRIVER: ${KC_DB_DRIVER}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_DB_URL: ${KC_DB_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8155:8080"
    depends_on:
      - db-dev
    command:
      - start-dev
    networks:
      - mt-network-dev

  backend-dev:
    build: ./backend
    container_name: mt-backend-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "8081:8000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db-dev
    networks:
      - mt-network-dev

  frontend-dev:
    build: ./frontend
    container_name: mt-frontend-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - backend-dev
    networks:
      - mt-network-dev

networks:
  mt-network-dev:
    driver: bridge

volumes:
  pgdata-dev: