services:
  keycloak-gw:
    image: keycloak/keycloak:26.3.2
    container_name: keycloak-gw
    env_file:
      - .env.dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_DRIVER: ${KC_DB_DRIVER}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_DB_URL: ${KC_DB_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8155:8080"
    depends_on:
      - postgres-gw
    command:
      - start-dev
    networks:
      - gw-network

  postgres-gw:
    image: postgres:15-alpine
    container_name: postgres-gw
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres-gw:/var/lib/postgresql/data
    networks:
      - gw-network

  redis:
    image: redis:7-alpine
    container_name: redis-gw
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  gw-network:
    driver: bridge

volumes:
  postgres-gw:
  redis-data: