spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8155/realms/api-gateway
        registration:
          keycloak:
            provider: keycloak
            client-id: oauth-client
            client-secret: DDuhebV1aHWJQYXobEzQWmrBySmIsTvk
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - roles

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: test-app
          uri: http://localhost:8081/
          predicates:
            - Path=/api/**
            - Method= GET
          filters:
            - TokenRelay=
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: TRACE
    org.springframework.cloud.gateway: DEBUG